/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LiveStreaming: typeof import('./src/components/LiveStreaming.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    MaterialList: typeof import('./src/components/MaterialList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    UserDashboard: typeof import('./src/components/UserDashboard.vue')['default']
    UserData: typeof import('./src/components/UserData.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    UserProjects: typeof import('./src/components/UserProjects.vue')['default']
    UserTeam: typeof import('./src/components/UserTeam.vue')['default']
    UserWork: typeof import('./src/components/UserWork.vue')['default']
  }
}
